

project:
  type: website

website:
  title: "Nicholas Giangreco"
  description: "This is Nick's online landing page."
  background: "primary"
  foreground: "secondary"
  search: true
  pinned: true
  collapse: true
  navbar:
    left:
      - icon: github
        href: https://github.com/ngiangre
      - icon: linkedin
        href: https://www.linkedin.com/in/nickgiangreco/
    right:
      - text: "Projects"
        file: content/projects/index.qmd
      - text: "About"
        file : content/about/index.qmd
      - text: "CV"
        href: content/cv/Nicholas_Giangreco_CV.pdf
  page-footer:
    background: transparent
    left: Made throug pain, sweat, and tears

format:
  html:
    page-layout: full
    smooth-scroll: true
    theme: pulse
    css: styles.css
    toc: false

editor: source
